### PR TITLE
feature(TestRunComments.svelte): Quoting when submitting new comment

### LINKED ISSUE #124: "Discussion" tab: please, add "reply" option to the message
"Discussion" tab: please, add "reply" option to the message.
It means if the reply is chosen, add user mention (@name) to the message body so the user will receive notificatrion

### PR DESCRIPTION
**Pull request by k0machi**
This commit adds a "Quote Reply" button to the Comment component,
allowing user to quote a specific comment when creating a new comment

Closes #124

### CODE REVIEW

**Comment by k0machi** [comment]
> Does it create a notification for the user I replies to?

No, this is to purely to copy comment text, if there's a user mention in the quote however, it will create a notification. 

For something like notifications for replies and such we need a subscription system for threads implemented first for it to not be too hacky.

**Comment by roydahan** [comment]
The whole purpose of the issue from @juliayakovlev, was to send a notification to someone, once there was a reply.

**Comment by k0machi** [comment]
I can append a mention on top of the reply to produce a notification this way, it's hacky but it's a start.

**Comment by juliayakovlev** [comment]
> I can append a mention on top of the reply to produce a notification this way, it's hacky but it's a start.

it would be great to add a mention because it's expected that the autor of replyed message will get notification

**Comment by k0machi** [comment]
Added comment author mention to emit a notification:
image

**Review by juliayakovlev — APPROVED** [review]

**Review by roydahan — APPROVED** [review]

**Comment by roydahan** [comment]
I think it’s good enough for now.

**Pull request merged**
