### PR TITLE
improvement(TestRun/Jenkins): Add error handling inside modal window

### PR DESCRIPTION
**Pull request by k0machi**
This commit changes the way errors are presented to the user during
rebuild and clone process, removing old notification toasts and instead
inlining those errors inside the modal windows themselves, allowing
better readability and easier error reporting. Additionally, Alert
Widget received a console to view all previous errors, along with the
source of the error.

### CODE REVIEW

**Comment by k0machi** [comment]
Demo: 
image

**Review by soyacz — COMMENTED** [review]
I don't know yet how it works, but assuming we have 'AlertStore' maybe we could review alerts (e.g. adding a button somewhere to view alerts). We could present them all in some kind of modal (or other place) - so we're not limited to testrun/jenkins?

**Comment by k0machi** [comment]
> I don't know yet how it works, but assuming we have 'AlertStore' maybe we could review alerts (e.g. adding a button somewhere to view alerts). We could present them all in some kind of modal (or other place) - so we're not limited to testrun/jenkins?

Yes, currently AlertStore is a just a queue, but we could make it into a bucket which could be viewed by the user later.

**Comment by soyacz** [comment]
> > I don't know yet how it works, but assuming we have 'AlertStore' maybe we could review alerts (e.g. adding a button somewhere to view alerts). We could present them all in some kind of modal (or other place) - so we're not limited to testrun/jenkins?
> 
> Yes, currently AlertStore is a just a queue, but we could make it into a bucket which could be viewed by the user later.

Is it feasible?

**Comment by k0machi** [comment]
> > > I don't know yet how it works, but assuming we have 'AlertStore' maybe we could review alerts (e.g. adding a button somewhere to view alerts). We could present them all in some kind of modal (or other place) - so we're not limited to testrun/jenkins?
> > 
> > 
> > Yes, currently AlertStore is a just a queue, but we could make it into a bucket which could be viewed by the user later.
> 
> Is it feasible?

Yes, the logic that does the queue behaviour is in `frontend/AlertWidget.svelte`, it could either store removed alerts in another collection and provide a button on the screen somewhere to view them (e.g. in the footer)

**Comment by soyacz** [comment]
> > > > I don't know yet how it works, but assuming we have 'AlertStore' maybe we could review alerts (e.g. adding a button somewhere to view alerts). We could present them all in some kind of modal (or other place) - so we're not limited to testrun/jenkins?
> > > 
> > > 
> > > Yes, currently AlertStore is a just a queue, but we could make it into a bucket which could be viewed by the user later.
> > 
> > 
> > Is it feasible?
> 
> Yes, the logic that does the queue behaviour is in `frontend/AlertWidget.svelte`, it could either store removed alerts in another collection and provide a button on the screen somewhere to view them (e.g. in the footer)

I think this is preferable option, so users can raise issues with more details always - not only for this case.

**Comment by k0machi** [comment]
> > > > > I don't know yet how it works, but assuming we have 'AlertStore' maybe we could review alerts (e.g. adding a button somewhere to view alerts). We could present them all in some kind of modal (or other place) - so we're not limited to testrun/jenkins?
> > > > 
> > > > 
> > > > Yes, currently AlertStore is a just a queue, but we could make it into a bucket which could be viewed by the user later.
> > > 
> > > 
> > > Is it feasible?
> > 
> > 
> > Yes, the logic that does the queue behaviour is in `frontend/AlertWidget.svelte`, it could either store removed alerts in another collection and provide a button on the screen somewhere to view them (e.g. in the footer)
> 
> I think this is preferable option, so users can raise issues with more details always - not only for this case.

Added:

image

**Review by fruch — APPROVED** [review]
LGTM

**Review by soyacz — APPROVED** [review]
LGTM

**Pull request merged**
