### PR TITLE
improvement(results): add copy button to tables

### PR DESCRIPTION
**Pull request by soyacz**
Users might want to put resutls into gh issues. Added a copy to markdown button in the corner of all results tables for easy copy it in a way that can be pasted to gh issue. When copy happens, info message appears to give a clear sign about it.

closes: https://github.com/scylladb/argus/issues/421

### CODE REVIEW

**Comment by soyacz** [comment]
example table:
image

**Review by k0machi — APPROVED** [review]

**Comment by fruch** [comment]
> example table: image

show us the markdown, i.e. paste here as example

**Comment by fruch** [comment]
> |  | P90 read [ms] | P99 read [ms] | duration [HH:MM:SS] |
> | --- | --- | --- | --- |
> | Cycle #&#8203;0 | 1.39 | 2.75 | 00:30:00 |
> 
> or e.g:
> |  | P90 read [ms] | P99 read [ms] | duration [HH:MM:SS] |
> | --- | --- | --- | --- |
> | Cycle #&#8203;1 | 3.43 | 6.12 | 00:25:48 |
> | Cycle #&#8203;2 | 2.90 | 5.48 | 00:18:39 |
> | Cycle #&#8203;3 | 2.57 | 4.53 | 00:17:12 |
> 

Can we add support for coloring ?

See
https://github.com/orgs/community/discussions/31570

**Comment by soyacz** [comment]
I didn't see a way to color whole cells, but values seems to do the job:
|  | P90 write [ms] | P90 read [ms] | P99 write [ms] | P99 read [ms] | duration [HH:MM:SS] |
| --- | --- | --- | --- | --- | --- |
| Cycle #&#8203;1 | $${\color{green}2.65}$$ | $${\color{green}4.15}$$ | $${\color{green}5.40}$$ | $${\color{red}13.46}$$ | $${\color{green}00:33:20}$$ |
| Cycle #&#8203;2 | $${\color{green}2.29}$$ | $${\color{green}3.61}$$ | $${\color{green}3.83}$$ | $${\color{green}8.47}$$ | $${\color{green}00:22:15}$$ |
| Cycle #&#8203;3 | $${\color{green}2.13}$$ | $${\color{green}3.12}$$ | $${\color{green}3.28}$$ | $${\color{green}6.20}$$ | $${\color{green}00:19:38}$$ |

**Comment by fruch** [comment]
> I didn't see a way to color whole cells, but values seems to do the job:

still better than black and white

**Review by k0machi — APPROVED** [review]

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
