### PR TITLE
Add scylla-operator package/version information

### PR DESCRIPTION
**Pull request by fruch**
* add those to web run info
* add those to issue template

Ref: https://github.com/scylladb/scylla-cluster-tests/pull/5512

### CODE REVIEW

**Comment by fruch** [comment]
@k0machi 

seems like the github actions is broken 
```
Version 3.10.3 was not found in the local cache
Error: Version 3.10.3 with arch x[6](https://github.com/scylladb/argus/actions/runs/3627446497/jobs/6117345629#step:3:7)4 not found
```

I think it's using an old version of get-python action

**Comment by k0machi** [comment]
@fruch I think it just wants latest 3.10 hotfix, so just update the version to 3.10.8

**Comment by fruch** [comment]
> @fruch I think it just wants latest 3.10 hotfix, so just update the version to 3.10.8

even better, we should be pining specific minor releases...

**Comment by fruch** [comment]
> > @fruch I think it just wants latest 3.10 hotfix, so just update the version to 3.10.8
> 
> even better, we should be pining specific minor releases...

and now it's works much better.

**Review by vponomaryov — APPROVED** [review]

**Pull request merged**
