### PR TITLE
feature(summary-widget): summary widget

### PR DESCRIPTION
**Pull request by soyacz**
View widged showing tests statuses and results per Scylla version. Each test can be expanded to see results (tables) with key metrics. Initial features:
1. Results summary by scylla version (date, scm revision)
2. passed tests are collapsed by default
3. not run tests marked as warning
4. hiding tables with all cells green ... many more but small ones.

caveats:
1. works only with scylla-server package
2. tests filtering based on release (oss vs enterprise) implementation is poor as will work only with scylla-master and scylla-enterprise argus releases
3. key metrics are hardcoded, followup issue: https://github.com/scylladb/qa-tasks/issues/1821

Did a refactor of ResultsTab - extracted ResultTable to be able to reuse it across different parts of Argus (like Summary Widget)

refs: https://github.com/scylladb/argus/issues/486

### CODE REVIEW

**Comment by soyacz** [comment]
preview on staging - see Performance Regression Tests View

**Comment by fruch** [comment]
filter button, are not collapsing with the job
image

**Comment by fruch** [comment]
I think the ability to copy the version string (including git sha), now it's displayed only on the dropdown, and it's not easy to copy anything from it.

**Comment by soyacz** [comment]
I think this one could be reviewed, @k0machi please check when you have the time

**Review by k0machi — APPROVED** [review]
LGTM

**Pull request merged**
