### PR TITLE
feature(AdminPanel): Quick toggles for Groups/Tests

### LINKED ISSUE #392: Enhancement - Add the ability to "enable/disable" groups and tests in Admin area from the top level
It would be really helpful to enable/disable a group or a test from the top level view without the need to "edit" it one by one.
e.g. having an "eye" icon next to the trash icon.

Screenshot 2024-07-15 at 14 21 02

### PR DESCRIPTION
**Pull request by k0machi**
This commits adds quick switches to enable/disable groups and tests
inside admin management panel

Fixes #392

### CODE REVIEW

**Comment by k0machi** [comment]
image

**Review by roydahan — APPROVED** [review]
LGTM.

**Comment by roydahan** [comment]
Anyone want to quickly review?
I need this functionality urgently for 2024.2

**Review by soyacz — APPROVED** [review]
LGTM

**Review by soyacz — APPROVED** [review]
LGTM

**Pull request merged**
