### PR TITLE
feature(WorkArea.svelte): Add global search to the Workspace

### PR DESCRIPTION
**Pull request by k0machi**
This commit adds a global search bar to the Workspace page. This bar
allows user to search Argus for any test, group or release names, as
well as specific run ids. The following hapens for each:
    
* Test: a Test selector is added and shown to the user.
* Group: all Tests from a Group are added to the selector.
* Release: a Grid View is shown to the user to pick a single group or
  test
* Test Run: a Test selector is added with a selected run automatically
  opened

### CODE REVIEW

**Comment by k0machi** [comment]
Needs #459 to be merged first.

**Comment by k0machi** [comment]
Demo:

https://github.com/user-attachments/assets/e522d888-29d8-4996-83c2-1717e859f3b1

**Comment by soyacz** [comment]
would be nice to show hint how it can be searched. E.g. in demo you used `release:5.4` - let's have a small legend on how to search (e.g maybe when clicking on search bar, before typing anything could show help?)

**Comment by k0machi** [comment]
> would be nice to show hint how it can be searched. E.g. in demo you used `release:5.4` - let's have a small legend on how to search (e.g maybe when clicking on search bar, before typing anything could show help?)

image

Added.

**Review by roydahan — APPROVED** [review]

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
