### PR TITLE
fix(sirenada): Add the ability to open issues to "siren", "siren-frontend" and "siren-devops"

### PR DESCRIPTION
**Pull request by temichus**
Add the ability to open issues to "siren", "siren-frontend" and "siren-devops"
fixes https://github.com/scylladb/argus/issues/267

### CODE REVIEW

**Comment by temichus** [comment]
Add the ability to open issues to "siren", "siren-frontend" and "siren-devops":
Screenshot from 2023-08-10 15-47-31

Template for siren tests:
Screenshot from 2023-08-10 15-47-50

siren repo option removed from regular tests: 
Screenshot from 2023-08-10 15-48-58

The original template for regular tests is not touched:
Screenshot from 2023-08-10 15-49-12

**Review by k0machi — APPROVED** [review]

**Review by rayakurl — COMMENTED** [review]
@temichus I think that there was some kind of mixup with the names. 

Cloud repositories are: sirenada - this is the cloud tests repo, IMO it should be renamed to siren-tests for clarity. 
Siren - is for backend developers,
Siren-frontend - for frontend developers
Siren-devops- for cloud devops

So we should have all 4 since sirenada should stay (and if it's not too complicated should be renamed to "siren-tests".)

The template I asked is for "siren" and "siren-frontend".

Hope that I made things clear, please let me know if you have questions.
Thanks

**Comment by temichus** [comment]
> @temichus I think that there was some kind of mixup with the names.
> 
> Cloud repositories are: sirenada - this is the cloud tests repo, IMO it should be renamed to siren-tests for clarity. Siren - is for backend developers, Siren-frontend - for frontend developers Siren-devops- for cloud devops
> 
> So we should have all 4 since sirenada should stay (and if it's not too complicated should be renamed to "siren-tests".)
> 

done:
Screenshot from 2023-08-11 10-54-54


> The template I asked is for "siren" and "siren-frontend".
> 

@rayakurl , Am I understanding correctly that now we have only one template across 4 repos?
Renamed button:
Screenshot from 2023-08-11 10-54-29


> I think that there was a mixup between "siren" and "sirenada" (AKA siren-tests) Hope that I made things clear, please let me know if you have questions. Thanks

**Comment by rayakurl** [comment]
@temichus - you understand correct,  we need 4 repos for the cloud.
But please rename "Siren issue template" to "Cloud issue template" for clarity.

**Comment by temichus** [comment]
> Cloud issue template
@rayakurl 
one more question. do you need "ScyllaDB" and "Scylla Cluster Tests" options for Siten tests or I can remove it?

**Comment by rayakurl** [comment]
@temichus - 

> > Cloud issue template
> > Fixed.
> > Screenshot from 2023-08-11 13-18-33
> 
> @rayakurl one more question. do you need "ScyllaDB" and "Scylla Cluster Tests" options for Siten tests or I can remove it?

No, we don't need them.thanks!

**Pull request merged**
