### PR TITLE
improvement(TestDashboard): Display per-group status bars

### LINKED ISSUE #301: Release Dashboard Screen - Add a summary per test group
As a user of the system who manages a release through the "Release Dashboard" screen, I would want to be able to see a detailed summary per "Test Group" (quite similar to what we have in "workspaces" screen).
Ideally, the summary will include a pass/failed/running rate (in percentages & numbers).

Screenshot 2023-11-16 at 18 39 32
Screenshot 2023-11-16 at 18 40 45

### PR DESCRIPTION
**Pull request by k0machi**
This adds a status bar to release dashboard groups, similar to the
global job status bar visible on the release dashboard.

Fixes #301

### CODE REVIEW

**Comment by k0machi** [comment]
image

**Comment by roydahan** [comment]
Looks nice, but almost fixing :)
Can we have numbers / percentages of pass/fail?

**Comment by k0machi** [comment]
> Looks nice, but almost fixing :) Can we have numbers / percentages of pass/fail?

image

What about this?

**Comment by k0machi** [comment]
> @k0machi
> 
> it's missing this for each one (just a progress bar doesn't help understand what's investigated and what not) image

Got it, will enable the widget breakdown

**Comment by k0machi** [comment]
image

Should `Not Run` and `Not planned` be included in this breakdown?

**Pull request merged**
